### ISSUE TITLE
Consider adding `Language: en-GB` to DESCRIPTION

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/packagetemplate#103]
Running spell check by default uses en-US and flags words spelt in en-GB. After adding `Language: en-GB` to DESCRIPTION these lines disappeared. See code snippet below

```R
spelling::spell_check_package()
#> DESCRIPTION does not contain 'Language' field. Defaulting to 'en-US'.
#> ...
#> recoded       cleanepi.Rmd:106
#> standardise   calculate_age.Rd:15
#> Standardise   cleanepi.Rmd:104
```

Since the epiverse collaboration has British institutions involved. It would make life easier to add this field to {packagetemplate} to reduce the number of false spelling mistakes that will be raised by using en-US by default.

**Comment by Bisaloo** [comment]
I took some time to consider it because I find it a bit awkward to default to English if a project with many non-native English speakers and where we aim at being language-inclusive.

However, as you pointed out, the current situation already defaults to English so, although not ideal, defaulting to `en-GB` seems like a incremental improvement relative to `en-US`.

Could you submit a PR for this please?
