### ISSUE TITLE
Consider adding ORCID and RECON to WORDLIST

### ISSUE THREAD

**Issue by bahadzie** [epiverse-trace/packagetemplate#104]
`ORCID` and `RECON` came up during spell check. I think they are fairly common and we should consider adding them to the WORDLIST file.

**Comment by Bisaloo** [comment]
The `WORDLIST` should not be edited manually but only with the `spelling::update_wordlist()` function.

Adding a couple of extra occurrences in packagetemplate would break this workflow and would likely not improve the workflow for package developers since they would have to run `spelling::update_wordlist()` in all cases to add the other exceptions.
