### ISSUE TITLE
Update `CITATION.cff` workflow causes noise in PRs

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/packagetemplate#128]
Hi 👋 I've been making pull requests to implement the fix from #126 throughout the packages. Quite a few of those pull requests are being made more noisey by the bot action that updates the CFF file.

As a result, the PR becomes unnecessarily clutter with more changes. The updated citation file seems like something that is relevant to update on the main branch - and wanted to ask here whether there is a specific reason the CFF gets updated on each PR? cc @Bisaloo 

https://github.com/epiverse-trace/packagetemplate/blob/49d07fc771fae591cfd9f76aeed34e10d8afa9a3/.github/workflows/update-citation-cff.yaml#L11

Happy to update the workflow if this was an unintended consequence/we would want to change this.

**Comment by Bisaloo** [comment]
Yes, the workflow is not ideal. @joshwlambert has expressed the same complaint some time ago for the `README.md` update.

At the moment though, there is no ideal workflow. You can see a more detailed discussion in the following issue: https://github.com/epinowcast/epinowcast/issues/379.

In other words, we could do what you are proposing but we would need to have a custom secret instead of the default `GITHUB_TOKEN` secret to be able to push to protected branches, and this secret would have write access to all repos across the organization.

I keep hesitating on which trade-off is best but I'm open to changing it if we feel the potential security risk (which we could partially mitigate by having a fine-grained token, requiring approval for workflows to run, etc.) is worth it for the improvement in usability.

**Comment by chartgerink** [comment]
Ahhh thanks @Bisaloo 🙏  I see and agree your point regarding the access rights (defeats the point of protecting `main` 😅).

Might it be an idea to create a pull request with the changes to the CFF file, if there are any relevant changes on main that cause such a change to CFF? This would reduce the noise in the rest of the PRs and keep maintenance to a minimum (pull request review).

**Comment by Bisaloo** [comment]
Another idea is that it could be an explicit action the contributor or the maintainer has to take right before merging. It would prevent having many update commits in the same PR.

Something like a comment `/citation` that would trigger the workflow.

**Comment by chartgerink** [comment]
That is an option - sounds like more work to create this kind of bot, but I may be missing something. My main goal is to reduce the amount of arbitrary actions one needs to take - from my experiences at JOSS remembering arbitrary commands regularly fail as well (I would type `editorialbot invite as reviewer` instead of `add as reviewer`) 

I would personally prefer for an action that only requires standard actions. Happy to work on whichever path we end up deciding though 😊

**Comment by Bisaloo** [comment]
> sounds like more work to create this kind of bot, but I may be missing something.

The basic version is not exactly a bot, but a GitHub Actions workflow monitoring PR comments. You can see an [example in the `r-lib/actions` repo](https://github.com/r-lib/actions/blob/v2-branch/examples/pr-commands.yaml).
But your points about added complexity and memory requirements are still valid :thinking: 

I'd lean towards the PR solution which, although not ideal, would still result in less noise that the current option.
We would still need to test render (but not commit) the `README.md` in PRs though to ensure `README.Rmd` is updated to stay in sync with the proposed changes.
